// Shared copy for the static build and interactive demos.
const vpasteCopy = {
    en: {
      "demo.light": "Light",
      "demo.dark": "Dark",
      "demo.noResults": "No matching items in this demo",
      "demo.settings": "Settings",
      "alt.searchCapture": "vPaste search: an expanded search field and matching clipboard cards with highlighted keywords",
      "alt.settingsCapture": "vPaste General settings with the System, Light and Dark theme menu open",
      "demo.label": "Interactive demo",
      "demo.preview": "Feature preview",
      "a11y.skip": "Skip to content",
      "a11y.menu": "Open menu",
      "a11y.closeMenu": "Close menu",
      "a11y.primaryNav": "Primary navigation",
      "a11y.home": "vPaste home",
      "a11y.language": "Language",
      "a11y.demoPlatform": "Demo platform",
      "a11y.projectFacts": "Project facts",
      "a11y.privacyFlow": "Local clipboard flow",
      "nav.experience": "One shortcut",
      "nav.formats": "Formats",
      "nav.workflow": "Customize",
      "nav.privacy": "Privacy",
      "nav.source": "Open source",
      "hero.kicker": "Every copy, clearly visible",
      "hero.slogan": "Your clipboard, one shortcut away",
      "hero.lede": "Keep copied text, images, links, colors, and files in clear visual cards, ready to find and paste with a shortcut",
      "hero.platforms": "Windows + macOS",
      "hero.local": "History stored locally",
      "hero.license": "GPL-3.0 open source",
      "action.download": "Download vPaste",
      "action.repository": "View source",
      "action.releases": "Download latest release",
      "shortcut.kicker": "One shortcut from any app",
      "shortcut.title": "When needed,\none shortcut away",
      "shortcut.body": "Bring up your history, paste into your current app, and tuck the panel away when you’re done, with multi-display support that follows your active screen",
      "shortcut.loop": "Bring it up, then tuck it away with the same shortcut",
      "usecases.kicker": "Visual clipboard history",
      "usecases.title": "See what you copied at a glance",
      "usecases.body": "Type, time, source app, and a useful preview on every card make even a long history easy to recognize and recover",
      "usecases.aria": "Clipboard use cases",
      "usecases.history": "Keep a running clipboard history",
      "usecases.historyBody": "Each copy is saved in time order, including text, images, links, and files",
      "usecases.snippets": "Keep the original format",
      "usecases.snippetsBody": "Preserve headings, lists, and tables, or paste as plain text when needed",
      "usecases.queue": "Paste queue",
      "usecases.queueBody": "Queue contact details, then fill each field with Ctrl / ⌘ + V",
      "usecases.drag": "Cross-app drag and drop",
      "usecases.dragBody": "Drag text, images, links or files into compatible apps—even multi-file records",
      "usecases.search": "Search across your history",
      "usecases.searchBody": "Search by text, page title, file path, or source app",
      "usecases.preview": "Preview before you paste",
      "usecases.previewBody": "Press Space to preview images, links or full text before pasting",
      "usecases.organize": "Filter, tag, and favorite",
      "usecases.organizeBody": "Filter by type, app, or date; add tags and favorites to group frequently used items",
      "formats.kicker": "Every format, easy to see",
      "formats.title": "The right card for every kind of content",
      "formats.body": "Text, images, links, colors, and files are sorted automatically, with the context you need to recognize, search, preview, and reuse them",
      "formats.text": "Text",
      "formats.textBody": "Keep headings, lists, and tables intact, then paste with the original formatting or as plain text",
      "formats.textFeature1": "Headings, tables & links",
      "formats.textFeature2": "Searchable content",
      "formats.textFeature3": "Formatted or plain paste",
      "formats.image": "Images",
      "formats.imageBody": "See the image in the card, inspect full detail, and export it whenever you need the file",
      "formats.imageFeature1": "Full-size preview",
      "formats.imageFeature2": "Dimensions & GIF detection",
      "formats.imageFeature3": "Export as an image file",
      "formats.link": "Links",
      "formats.linkBody": "With link previews enabled, cards include the page title and preview image",
      "formats.linkFeature1": "Title & preview image",
      "formats.linkFeature2": "Preview before opening",
      "formats.linkFeature3": "Search title or URL",
      "formats.color": "Colors",
      "formats.colorBody": "See the swatch and its value together, then convert between common color formats",
      "formats.colorFeature1": "HEX / RGB / HSL",
      "formats.colorFeature2": "Live color swatch",
      "formats.colorFeature3": "One-click conversion",
      "formats.file": "Files",
      "formats.fileBody": "Keep files, folders, and multi-file copies ready to preview, locate, or send again",
      "formats.fileFeature1": "Single files, folders & batches",
      "formats.fileFeature2": "Preview common content",
      "formats.fileFeature3": "Open location or copy path",
      "search.kicker": "Remember a little, find the rest",
      "search.title": "Search whatever you remember",
      "search.body": "Enter the fragment you remember, then narrow the results by type, source app, favorite, tag, or time",
      "search.point1": "Text and rich-text keywords",
      "search.point2": "Page titles, URLs, file names & paths",
      "search.point3": "Type, source, favorites, tags & time",
      "workflow.kicker": "Work your way",
      "workflow.title": "Make vPaste feel natural to use",
      "workflow.body": "Adjust themes, shortcuts, and history settings to suit your workflow",
      "settings.behaviorBody": "Follow your system or choose light or dark, with English and Chinese interfaces",
      "settings.experienceBody": "Show link titles and images, and remember your search, tab, and scroll position",
      "settings.dataBody": "Choose a storage folder, clean up old records, or migrate your complete history",
      "settings.shortcutsBody": "Set your panel shortcut and use the keyboard to search, preview, and choose a paste format",
      "alt.localArtwork": "A desktop archive of paper records beside a portable drive, illustrating local history and migration",
      "settings.behavior": "Interface & behavior",
      "settings.behavior1": "System, light, and dark themes",
      "settings.behavior2": "English and Simplified Chinese",
      "settings.behavior3": "Startup, tray, and background behavior",
      "settings.experience": "Clipboard experience",
      "settings.experience1": "Rich link titles and preview images",
      "settings.experience2": "Remember search, tab, and scroll position",
      "settings.experience3": "Source app names and icons",
      "settings.data": "Data & privacy",
      "settings.data1": "Skip sensitive content and selected apps",
      "settings.data2": "Choose the history storage folder",
      "settings.data3": "Review storage and clean history by age",
      "settings.data4": "Move complete history between installations",
      "settings.shortcuts": "Keyboard workflow",
      "settings.shortcuts1": "Show or hide the panel from any app",
      "settings.shortcuts2": "Paste with formatting or as plain text",
      "settings.shortcuts3": "Select with arrows, Tab, and Alt",
      "settings.shortcuts4": "Search, preview, and open actions by keyboard",
      "privacy.kicker": "Local history, your control",
      "privacy.title": "Stored on your device,\nnever uploaded",
      "privacy.body": "vPaste keeps clipboard history on your device without uploading it, with exclusions for selected apps and sensitive content and optional link previews that request the linked pages",
      "privacy.localDb": "Clipboard history stored on your device",
      "privacy.control": "Sensitive-content and per-app exclusions",
      "privacy.feature1": "Copied content is saved automatically on your device",
      "privacy.feature2": "Exclude sensitive content and selected apps",
      "privacy.feature3": "Choose storage location and clear older records",
      "privacy.feature4": "Manually transfer history between Windows and macOS",
      "privacy.feature5": "Optional link previews request the linked page",
      "data.onDevice": "On your device",
      "data.migrate": "Move your history",
      "data.clean": "Clear older records",
      "demo.older": "More history, still here",
      "demo.keepFormat": "Headings, lists and tables stay intact",
      "demo.plainText": "Paste as plain text when needed",
      "demo.spacePreview": "Preview the selected item",
      "demo.readme": "A clipboard workspace for text, images, links and files",
      "demo.workNote": "Project notes",
      "demo.projectNote": "Collected for this project",
      "demo.dropHere": "Drop an image into your document",
      "demo.saved": "Saved on this device",
      "demo.manualMigration": "Manual migration",
      "demo.exportImport": "Export, then import to move history between Windows and macOS",
      "demo.transferAction": "Export → Import",
      "demo.typeSearch": "Type to search",
      "demo.value.email": "hello@example.com",
      "demo.value.address1": "18 Market Street",
      "demo.value.address2": "Suite 240",
      "demo.value.postal": "94105",
      "product.project": "Project",
      "demo.formTitle": "Shipping details",
      "demo.email": "Email",
      "demo.address1": "Address line 1",
      "demo.address2": "Address line 2",
      "demo.postal": "Postal code",
      "demo.queueNext": "Next up",
      "demo.queueEmpty": "Queue empty",
      "demo.queueCopy": "Copy into the queue",
      "demo.queuePaste": "Paste into each field",
      "demo.pause": "Pause demo",
      "demo.resume": "Play demo",
      "privacy.flowCopy": "Copy",
      "privacy.flowStore": "Check privacy",
      "privacy.flowFind": "Store locally",
      "privacy.flowPaste": "Find & paste",
      "privacy.orbitLabel": "Local",
      "privacy.orbitCore": "Clipboard history",
      "source.kicker": "Open source makes the promise inspectable",
      "source.title": "Open from source code to security policy",
      "source.body": "vPaste is GPL-3.0 open source, with Windows and macOS desktop code, platform integrations, release history, and a security policy open for anyone to inspect",
      "source.factOpen": "Auditable source",
      "source.factLocal": "Local history architecture",
      "source.factPrivate": "Clipboard history is stored on your device",
      "source.factPlatforms": "Platform-specific clipboard handling",
      "final.kicker": "Browse clipboard history as cards, call it up fast, paste in one step",
      "final.title": "Your clipboard, one shortcut away",
      "product.all": "All",
      "product.favorites": "Favorites",
      "product.text": "Text",
      "product.images": "Images",
      "product.links": "Links",
      "product.colors": "Colors",
      "product.files": "Files",
      "product.search": "Search clipboard history",
      "product.timeSeconds": "A few seconds ago",
      "product.timeMinutes": "4 minutes ago",
      "product.timeTenHours": "10 hours ago",
      "product.timeHours": "2 hours ago",
      "product.timeHoursLong": "6 hours ago",
      "product.timeYesterday": "Yesterday",
      "product.textTitle": "vPaste",
      "product.textDescription": "Your clipboard, one shortcut away",
      "product.linkTitle": "Loxonl/vPaste-desktop",
      "product.fileName": "C:/Demo/vPaste Intro.pdf",
      "product.filterState": "Showing image items",
      "product.word": "Microsoft Word",
      "product.wechat": "WeChat",
      "product.chrome": "Google Chrome",
      "product.explorer": "File Explorer",
      "product.figma": "Figma",
      "product.excel": "Microsoft Excel",
      "product.tableContent": "Content",
      "product.tableType": "Type",
      "product.tableResult": "Result",
      "product.tableText": "vPaste text",
      "product.tablePlain": "Plain text",
      "product.tableSearchable": "Searchable",
      "product.tableLink": "Link",
      "product.tableTitleKept": "Title kept",
      "product.tableColor": "Color",
      "product.tableValueShown": "Value shown",
      "product.codeTitle": "Code snippet",
      "product.replyTitle": "Reusable reply",
      "product.addressTitle": "Shipping address",
      "product.codeBody": "const openHistory = () => invoke(\"show_main_window\");",
      "product.replyBody": "Thanks, I have reviewed the details and will follow up today",
      "product.addressBody": "18 Market Street, Suite 240\nSan Francisco, CA",
      "product.smartFilters": "Smart Filters",
      "product.smartFiltersBody": "Match type, app, or keywords",
      "product.manualTags": "Manual Tags",
      "product.manualTagsBody": "Mark individual items yourself",
      "product.filterText": "Text from Word",
      "product.filterLinks": "Links from Chrome",
      "product.tagLaunch": "Launch copy",
      "product.tagReference": "Reference",
      "product.previewTitle": "Clipboard preview",
      "product.previewBody": "Preview copied text, images, links, files, and rich formatting before pasting them back into your work",
      "product.general": "General",
      "product.data": "Data",
      "product.shortcuts": "Shortcuts",
      "product.about": "About",
      "product.system": "System settings",
      "product.startup": "Launch at startup",
      "product.tray": "Show tray icon",
      "product.language": "Language",
      "product.theme": "Theme",
      "product.tutorial": "Tutorial",
      "product.open": "Open",
      "product.personalization": "Personalization",
      "product.linkPreview": "Link auto preview",
      "product.keepSearch": "Keep search history",
      "product.linkPreviewDesc": "Rich context for copied URLs",
      "product.keepSearchDesc": "Resume the previous query",
      "product.languageValue": "English",
      "product.themeValue": "System",
      "alt.main": "vPaste clipboard history window with typed tabs and recent clipboard items",
      "alt.shortcut": "vPaste appearing over the desktop",
      "alt.formats": "Abstract stack of clipboard content formats",
      "alt.tabs": "vPaste custom filter tabs",
      "alt.preview": "vPaste clipboard item preview",
      "alt.settings": "vPaste settings window",
      "alt.vault": "Abstract local data vault receiving clipboard layers",
      "meta.title": "vPaste — Visual Clipboard Manager for Windows & macOS",
      "meta.description": "vPaste is a local clipboard manager for Windows and macOS that automatically organizes text, images, links, colors, and files into visual cards for fast search, preview, and reuse",
    },
    zh: {
      "demo.light": "浅色",
      "demo.dark": "深色",
      "demo.noResults": "演示记录中没有匹配内容",
      "demo.settings": "设置",
      "alt.searchCapture": "vPaste 正式搜索界面：顶部展开搜索框，下方显示带关键词高亮的剪贴卡片",
      "alt.settingsCapture": "vPaste 通用设置页，展开跟随系统、浅色模式和深色模式的主题菜单",
      "demo.label": "交互演示",
      "demo.preview": "功能示意",
      "a11y.skip": "跳到主要内容",
      "a11y.menu": "打开菜单",
      "a11y.closeMenu": "关闭菜单",
      "a11y.primaryNav": "主要导航",
      "a11y.home": "vPaste 首页",
      "a11y.language": "语言",
      "a11y.demoPlatform": "演示平台",
      "a11y.projectFacts": "项目概况",
      "a11y.privacyFlow": "本机剪贴处理流程",
      "nav.experience": "一键呼出",
      "nav.formats": "内容格式",
      "nav.workflow": "个性设置",
      "nav.privacy": "隐私",
      "nav.source": "开源",
      "hero.kicker": "每次复制，都清晰可见",
      "hero.slogan": "剪贴捷径，一键即达",
      "hero.lede": "把复制过的文本、图片、链接、颜色与文件留在清晰的卡片里，随时快捷呼出、搜索并粘贴",
      "hero.platforms": "Windows + macOS",
      "hero.local": "历史存于本机",
      "hero.license": "GPL-3.0 开源",
      "action.download": "下载 vPaste",
      "action.repository": "查看源码",
      "action.releases": "下载最新版本",
      "shortcut.kicker": "从任意应用一键呼出",
      "shortcut.title": "需要时，\n一键呼出",
      "shortcut.body": "快捷呼出历史，选取内容粘贴回当前应用，用完再收起，多屏时跟随当前操作",
      "shortcut.loop": "同一个快捷键，呼出窗口，也能再次收起",
      "usecases.kicker": "可视化剪贴历史",
      "usecases.title": "复制了什么，一眼就知道",
      "usecases.body": "类型、时间、来源应用和内容预览都在卡片上，历史再多也能快速辨认和找回",
      "usecases.aria": "剪贴板用途场景",
      "usecases.history": "持续记录复制历史",
      "usecases.historyBody": "每次复制自动保存，文本、图片、链接与文件按时间排列",
      "usecases.snippets": "保留原有格式",
      "usecases.snippetsBody": "标题、列表和表格保留结构，也可按需要粘贴为纯文本",
      "usecases.queue": "粘贴队列",
      "usecases.queueBody": "邮箱、地址、邮编，按队列顺序用 Ctrl / ⌘ + V 逐项填表",
      "usecases.drag": "跨应用拖拽",
      "usecases.dragBody": "文本、链接、图片与文件可拖入支持的应用，多文件也能一起拖出",
      "usecases.search": "搜索历史记录",
      "usecases.searchBody": "输入正文、网页标题、文件路径或来源应用，查找对应记录",
      "usecases.preview": "粘贴前先预览",
      "usecases.previewBody": "按 Space 查看大图、链接与完整内容，确认后再粘贴",
      "usecases.organize": "分类、标签与收藏",
      "usecases.organizeBody": "按类型、应用或日期筛选，用标签和收藏整理常用内容",
      "formats.kicker": "每种内容，都看得清楚",
      "formats.title": "不同内容自有合适的卡片",
      "formats.body": "文本、图片、链接、颜色和文件会自动分类，并保留辨认、搜索、预览与再次使用所需的信息",
      "formats.text": "文本",
      "formats.textBody": "保留标题、列表和表格结构，可按原格式或纯文本粘贴",
      "formats.textFeature1": "标题、表格与链接",
      "formats.textFeature2": "正文关键词可搜索",
      "formats.textFeature3": "原格式或纯文本粘贴",
      "formats.image": "图片",
      "formats.imageBody": "缩略图直接展示内容，可查看完整细节并导出复用",
      "formats.imageFeature1": "完整图片预览",
      "formats.imageFeature2": "分辨率与 GIF 识别",
      "formats.imageFeature3": "导出为图片文件",
      "formats.link": "链接",
      "formats.linkBody": "开启链接预览后，卡片自动补全网页标题与预览图",
      "formats.linkFeature1": "标题与预览图",
      "formats.linkFeature2": "粘贴前查看页面",
      "formats.linkFeature3": "标题和网址都可搜索",
      "formats.color": "颜色",
      "formats.colorBody": "色块与数值同时可见，常用颜色格式可以快速转换",
      "formats.colorFeature1": "HEX / RGB / HSL",
      "formats.colorFeature2": "真实色块预览",
      "formats.colorFeature3": "一键转换颜色格式",
      "formats.file": "文件",
      "formats.fileBody": "保留文件、文件夹和多文件记录，稍后仍可预览、定位和再次发送",
      "formats.fileFeature1": "单个、多个或文件夹",
      "formats.fileFeature2": "常见内容预览",
      "formats.fileFeature3": "打开位置或复制路径",
      "search.kicker": "记得一点，就能找到",
      "search.title": "记得什么就搜什么",
      "search.body": "输入记得的片段，再按类型、来源应用、收藏、标签或时间缩小范围",
      "search.point1": "文本与富文本关键词",
      "search.point2": "网页标题、网址、文件名与路径",
      "search.point3": "类型、来源、收藏、标签与时间",
      "workflow.kicker": "按你的习惯工作",
      "workflow.title": "把 vPaste 调成顺手的样子",
      "workflow.body": "主题、快捷键与历史管理，按习惯设置",
      "settings.behaviorBody": "外观可跟随系统或选择深浅主题，支持中文与英文界面",
      "settings.experienceBody": "显示链接标题与缩略图，记住上次的搜索、标签和滚动位置",
      "settings.dataBody": "自选存储目录，按时间清理旧记录，也能迁移完整历史",
      "settings.shortcutsBody": "自定义呼出快捷键，用键盘搜索、预览，并选择粘贴格式",
      "alt.localArtwork": "纸质记录收纳盒与便携硬盘，表达本地历史的保存与迁移",
      "settings.behavior": "界面与行为",
      "settings.behavior1": "跟随系统、浅色与深色主题",
      "settings.behavior2": "英文与简体中文界面",
      "settings.behavior3": "开机启动、托盘与后台运行",
      "settings.experience": "剪贴板体验",
      "settings.experience1": "链接标题与预览图自动补全",
      "settings.experience2": "记住搜索、标签与滚动位置",
      "settings.experience3": "记录来源应用名称与图标",
      "settings.data": "数据与隐私",
      "settings.data1": "跳过敏感内容与指定应用",
      "settings.data2": "自行选择历史数据存储位置",
      "settings.data3": "统计空间并按时间清理历史",
      "settings.data4": "在不同安装之间迁移完整历史",
      "settings.shortcuts": "键盘工作流",
      "settings.shortcuts1": "从任意应用呼出或收起面板",
      "settings.shortcuts2": "保留格式粘贴或粘贴为纯文本",
      "settings.shortcuts3": "方向键、Tab 与 Alt 快速选择",
      "settings.shortcuts4": "用键盘搜索、预览并打开操作菜单",
      "privacy.kicker": "本机存储，数据自主",
      "privacy.title": "记录留在本机，\n不上传服务器",
      "privacy.body": "vPaste 将剪贴历史保存在本机、不上传服务器，支持排除指定应用和敏感内容，开启链接预览时会请求链接指向的网页",
      "privacy.localDb": "剪贴历史保存在你的设备上",
      "privacy.control": "敏感内容保护与指定应用排除",
      "privacy.feature1": "复制内容自动保存在本机",
      "privacy.feature2": "可排除敏感内容与指定应用",
      "privacy.feature3": "自选存储位置，按时间清理历史",
      "privacy.feature4": "在 Windows 与 macOS 之间手动迁移历史",
      "privacy.feature5": "链接预览开启时才请求对应网页",
      "data.onDevice": "留在你的设备上",
      "data.migrate": "迁移完整历史",
      "data.clean": "按时间清理历史",
      "demo.older": "更早的记录，也在这里",
      "demo.keepFormat": "标题、列表与表格，保留原有格式",
      "demo.plainText": "需要时，也能粘贴为纯文本",
      "demo.spacePreview": "预览当前选中的内容",
      "demo.readme": "收纳文本、图片、链接与文件的剪贴板工作台",
      "demo.workNote": "项目笔记",
      "demo.projectNote": "为这个项目收集的内容",
      "demo.dropHere": "把图片拖入文档",
      "demo.saved": "持续保存在本机",
      "demo.manualMigration": "手动迁移",
      "demo.exportImport": "先导出，再导入，在 Windows 与 macOS 之间手动迁移历史",
      "demo.transferAction": "导出 → 导入",
      "demo.typeSearch": "输入关键词搜索",
      "demo.value.email": "hello@example.com",
      "demo.value.address1": "示例路 18 号",
      "demo.value.address2": "创意中心 240 室",
      "demo.value.postal": "200000",
      "product.project": "项目",
      "demo.formTitle": "收件信息",
      "demo.email": "电子邮箱",
      "demo.address1": "地址 1",
      "demo.address2": "地址 2",
      "demo.postal": "邮编",
      "demo.queueNext": "下一项",
      "demo.queueEmpty": "队列为空",
      "demo.queueCopy": "依次复制入队",
      "demo.queuePaste": "按顺序填入表单",
      "demo.pause": "暂停演示",
      "demo.resume": "播放演示",
      "privacy.flowCopy": "复制",
      "privacy.flowStore": "检查隐私规则",
      "privacy.flowFind": "本机保存",
      "privacy.flowPaste": "查找并粘贴",
      "privacy.orbitLabel": "本机",
      "privacy.orbitCore": "剪贴历史",
      "source.kicker": "开源，也让承诺可核验",
      "source.title": "从代码到安全策略全程公开",
      "source.body": "vPaste 采用 GPL-3.0 开源，Windows 与 macOS 桌面端代码、平台适配、发布记录和安全策略均可公开查阅",
      "source.factOpen": "代码可审查",
      "source.factLocal": "本机历史架构",
      "source.factPrivate": "剪贴历史保存在你的设备上",
      "source.factPlatforms": "针对平台处理原生剪贴格式",
      "final.kicker": "卡片浏览剪贴历史，快速呼出，一键粘贴",
      "final.title": "剪贴捷径，一键即达",
      "product.all": "全部",
      "product.favorites": "收藏",
      "product.text": "文本",
      "product.images": "图片",
      "product.links": "链接",
      "product.colors": "颜色",
      "product.files": "文件",
      "product.search": "搜索剪贴板历史",
      "product.timeSeconds": "几秒前",
      "product.timeMinutes": "4 分钟前",
      "product.timeTenHours": "10 小时前",
      "product.timeHours": "2 小时前",
      "product.timeHoursLong": "6 小时前",
      "product.timeYesterday": "昨天",
      "product.textTitle": "vPaste",
      "product.textDescription": "剪贴捷径，一键即达",
      "product.linkTitle": "Loxonl/vPaste-desktop",
      "product.fileName": "C:/Demo/vPaste Intro.pdf",
      "product.filterState": "正在显示图片内容",
      "product.word": "Microsoft Word",
      "product.wechat": "微信",
      "product.chrome": "Google Chrome",
      "product.explorer": "文件资源管理器",
      "product.figma": "Figma",
      "product.excel": "Microsoft Excel",
      "product.tableContent": "内容",
      "product.tableType": "类型",
      "product.tableResult": "结果",
      "product.tableText": "vPaste 文本",
      "product.tablePlain": "纯文本",
      "product.tableSearchable": "可搜索",
      "product.tableLink": "链接",
      "product.tableTitleKept": "保留标题",
      "product.tableColor": "颜色",
      "product.tableValueShown": "显示色值",
      "product.codeTitle": "代码片段",
      "product.replyTitle": "常用回复",
      "product.addressTitle": "收货地址",
      "product.codeBody": "const openHistory = () => invoke(\"show_main_window\");",
      "product.replyBody": "谢谢，详细信息已经确认，我会在今天继续跟进",
      "product.addressBody": "上海市静安区灵石路 18 号\n创意中心 240 室",
      "product.smartFilters": "自动筛选",
      "product.smartFiltersBody": "按类型、应用或关键词自动匹配",
      "product.manualTags": "手动标记",
      "product.manualTagsBody": "自行标记具体的剪贴内容",
      "product.filterText": "Word 文本",
      "product.filterLinks": "Chrome 链接",
      "product.tagLaunch": "发布文案",
      "product.tagReference": "参考资料",
      "product.previewTitle": "剪贴内容预览",
      "product.previewBody": "粘贴前先确认复制过的文本、图片、链接、文件和富文本格式，再把它们带回当前工作",
      "product.general": "通用",
      "product.data": "数据",
      "product.shortcuts": "快捷键",
      "product.about": "关于",
      "product.system": "系统设置",
      "product.startup": "开机启动",
      "product.tray": "显示托盘图标",
      "product.language": "多语言",
      "product.theme": "主题模式",
      "product.tutorial": "使用向导",
      "product.open": "打开",
      "product.personalization": "个性化",
      "product.linkPreview": "链接自动预览",
      "product.keepSearch": "保留搜索记录",
      "product.linkPreviewDesc": "为复制的链接保留丰富上下文",
      "product.keepSearchDesc": "再次打开时恢复上一次搜索",
      "product.languageValue": "简体中文（大陆）",
      "product.themeValue": "跟随系统",
      "alt.main": "vPaste 主剪贴板历史窗口，展示类型标签和近期记录",
      "alt.shortcut": "vPaste 从桌面上方呼出",
      "alt.formats": "由多种剪贴板内容组成的抽象堆栈",
      "alt.tabs": "vPaste 自定义筛选标签",
      "alt.preview": "vPaste 剪贴内容预览",
      "alt.settings": "vPaste 设置窗口",
      "alt.vault": "接收剪贴板内容的抽象本地数据仓",
      "meta.title": "vPaste｜Windows 与 macOS 可视化剪贴板管理器",
      "meta.description": "vPaste 是一款本机存储的 Windows 与 macOS 剪贴板管理器，用可视化卡片自动分类文本、图片、链接、颜色与文件，支持快速搜索、预览和再次粘贴",
    },
  };
if (typeof module !== "undefined") module.exports = vpasteCopy;
else window.vpasteCopy = vpasteCopy;
